#' Calculating significance by permutations
#'
#' \code{Calculate_permutationSignificance} estimates the significance of the actual PRS based on permutations of
#'   random sets of SNPs matching the actual SNP set by several properties.The random sets are generated by the
#'   \code{Generate_permutationSets} function of this package. The result is saved in a file.
#'
#' @param path.to.plink.files String with the full path to the three PLINK binary files (.bed, .bim, .fam).
#' @param bfile A string indicating the name of the PLINK binary file with data of the GWAS target sample, without extension.
#'   The tmp files generated by the \code{Calculate_DR2Nagelkerke} function are used by default. If other files are used, the "snpid" column 
#'   has to be identified as chr:pos (such as 4:103334).
#' @param sumGWAS A dataframe with a minimum of these columns "chr.pos", "a1", "p", "logOR", taken from the summary
#'   statistics of the GWAS discovery sample.
#' @param Perm A dataframe with the permuted SNP sets, generated by the \code{Generate_permutationSets} function of this package.
#' @param DR2 A number corresponding to the value of the increase in pseudo-R2 of Naglekerke of the actual SNP set. It is the
#'   first element of the list generated by the \code{calculate_DR2Nagelkerke} function of this package.
#' @param Cov A dataframe with a column "IID"  for sample identification and covariates with specific names.
#' @param cov.names An array with the names of covariates from the \code{Cov} dataframe to be included in the model.
#' @param outfile A string indicating the name of the output file to write the P value. This file
#'   is generated in the path defined in \code{path.to.plink.files}.
#'
#' @return A list with two elements. The first element is a number representing the permuted P value. The second element is
#'    an array with the pseudo-R2 values of the permuted data sets.


Calculate_permutationSignificance <- function(path.to.plink.files, bfile = "tmp", sumGWAS, Perm, Cov = NULL, DR2,
                                              cov.names, outfile) {

  # Basic check of input files
  if (!"snpid"  %in% colnames(sumGWAS)) stop("No \"snpid\" column in sumGWAS")
  if (!"a1"  %in% colnames(sumGWAS)) stop("No \"a1\" column in sumGWAS")
  if (!"p"  %in% colnames(sumGWAS)) stop("No \"p\" column in sumGWAS")
  if (!"effect"  %in% colnames(sumGWAS)) stop("No \"effect\" column in sumGWAS")
  # Basic check of covariates file
  if (!is.null(Cov)){
    if (!("IID" %in% colnames(Cov))) stop("No \"IID\" column in Cov")
    if (length(subset(cov.names,cov.names %in% colnames(Cov))) != length(cov.names)) stop("Some covariate names in cov.names are not in the Cov dataframe")
    if (is.null(cov.names)) stop ("Covariates names no specified")
  }
  if (is.null(Cov) & !is.null(cov.names)) stop("Covariate names specified but covariate file is lacked")
  
  IncrR2 <- rep()
  for (i in 1:dim(Perm)[2]) {

    #----------------
    # Calculate PRS
    #---------------

    # Data for PRS
    SNPs <- subset(sumGWAS, sumGWAS$snpid %in% Perm[, i])
    PRS.model <- SNPs[, c("snpid", "a1", "effect")]
    name <- paste(path.to.plink.files, "PRSmodel", sep="")
    write.table(PRS.model, file = name, append = F, quote = F, sep = "\t", row.names = F, col.names = F)
    # Calculate PRS using PLINK
    arg1 <- paste("--bfile", paste0(path.to.plink.files, bfile), sep=" ")
    arg2 <- paste("--score", paste0(path.to.plink.files, "PRSmodel"), sep=" ")
    arg3 <- paste("--out", paste0(path.to.plink.files, "Scores"), sep=" ")
    system2("plink", args = c(arg1, arg2, arg3))
    path <- paste0(path.to.plink.files, "Scores.PROFILE")
    Scores <- read.table(path, header = T)

   #---------------------------------------------
   # Statistical analysis by logistic regression
   #---------------------------------------------

    # Merge covariables with score, if any
    if (is.null(Cov)) {
      data <- Scores
      # Calculating % missing
      data$percent_missing <- (max(data$CNT) - data$CNT) / max(data$CNT)
      # Covariables
      pheno <- data$PHENO
      score <- data$SCORE
      miss <- data$percent_missing
      #Standardized score
      st.score <- scale(score)
      # If there is no missing, there was an error in logistic regression. Check
      max.missing<-max(miss)
      if (max.missing > 0) {
        H0 <- rms::lrm(pheno ~ miss, tol = 0)
        H1 <- rms::lrm(pheno ~ miss + st.score, tol = 0)
        # Increase in Nagelkerke's pseudo-R2
        permDR2 <- (H1$stats[10] - H0$stats[10])
      } else {
        H1 <- rms::lrm(pheno ~ st.score, tol = 0)
        permDR2 <- (H1$stats[10])
      }
    } else if (!is.null(Cov)){

      # Choosing covariates
      cov.for.used <- colnames(Cov) %in% cov.names
      used.cov <- as.data.frame(Cov[, cov.for.used])
      if (length(cov.names) == 1) colnames(used.cov) <- cov.names#If there is just one covariate, coercing to dataframe implies lost of colname
      used.cov$IID <- Cov$IID
      used.cov.ord <- used.cov[order(used.cov$IID), ]
      Scores.ord <- Scores[order(Scores$IID), ]
      for (i in 1:dim(used.cov.ord)[2]) {
        assign(colnames(used.cov.ord)[i], used.cov.ord[, i])
      }
      pheno <- Scores.ord$PHENO
      score <- Scores.ord$SCORE
      # Standardized score
      st.score <- scale(score)
      names <- cov.names[1]
      if (length(cov.names) > 1) {
        for (i in 2:length(cov.names)) {
        names <- paste(names, cov.names[i], sep="+")
        }
      }  
   
      # If there is no missing, there was an error in logistic regression. Check
      Scores.ord$percent_missing <- (max(Scores.ord$CNT) - Scores.ord$CNT) / max(Scores.ord$CNT)
      miss <- Scores.ord$percent_missing
      max.missing <- max(miss)
      if (max.missing > 0) {
        formula.m0 <- as.formula(paste("pheno ~ miss", names, sep="+"))
        formula.m1 <- as.formula(paste("pheno ~ st.score + miss", names, sep="+"))
        H0 <- rms::lrm(formula.m0, tol = 0)
        H1 <- rms::lrm(formula.m1, tol = 0)
        # Increase in Nagelkerke's R2
        permDR2 <- (H1$stats[10] - H0$stats[10])
      } else {
        formula.m0 <- as.formula(paste("pheno ~ ",names, sep="+"))
        H0 <- rms::lrm(formula.m0, tol = 0)
        formula.m1 <- as.formula(paste("pheno  ~ st.score", names, sep="+"))
        H1 <- rms::lrm(formula.m1, tol = 0)
        # Increase in Nagelkerke's R2
        permDR2 <- (H1$stats[10] - H0$stats[10])
      }
    }
  IncrR2 <- c(IncrR2, permDR2)
  }
  #-----------------------------------------------------------------------------

  # Calculate P, following:
  # Phipson, B., and Smyth, G. K. (2010). Permutation p-values should never be zero: calculating exact
  # p-values when permutations are randomly drawn. Stat. Appl. Genet. Molec. Biol. Volume 9, Issue
  # 1, Article 39.

  actual.value <- DR2
  perm.DeltaR2 <- as.numeric(IncrR2)
  higher <- perm.DeltaR2 > actual.value
  h <- sum(higher, na.rm = TRUE)
  P <- (h + 1) / (dim(Perm)[2] + 1)

  # Writing main results to a file
  file.name <- paste0(path.to.plink.files, outfile)
  sink(file.name)
  cat("The number of permuted pseudo-R2 scores higher than the actual one is: ",h,"\n\n")
  cat("The permuted P value is:",P)
  sink()

  res <- list(Permuted.P = P, DR2.permutations = perm.DeltaR2)
  
  message("The permuted P value is: ",P)

return(res)

}




